### ISSUE TITLE
My Css Configurations doesn't apply (sometimes)

### ISSUE THREAD

**Issue by Ahmadre** [twinssbc/Ionic2-Calendar#333]
I changed the default calendar css styles with my own ones like:
```css
page-calendar {
    [_nghost-c0] > div[_ngcontent-c0] {
        height: 100% !important;
    }

    .swiper-slide {
        align-items: unset !important;
    }

    .table[_ngcontent-c1] {
        height: 100% !important;
    }

    .table-bordered[_ngcontent-c1] > thead[_ngcontent-c1] > tr[_ngcontent-c1] > th[_ngcontent-c1], .table-bordered[_ngcontent-c1] > thead[_ngcontent-c1] > tr[_ngcontent-c1] > td[_ngcontent-c1] {
        border-bottom-width: 0 !important;
    }

    .monthview-datetable[_ngcontent-c1] th[_ngcontent-c1] {
        text-align: left !important;
        height: 24px !important;
    }

    .monthview-datetable[_ngcontent-c1] td[_ngcontent-c1] {
        text-align: left !important;
        height: 110px !important;
    }
...
```

My Calendar should look like this:
![datetimepicker](https://user-images.githubusercontent.com/18512224/39969746-f5e661e6-56e0-11e8-9877-c19d7a284d72.png)

but is sometimes looking like this:
![18567508-5e51-4377-b421-cf689da0952b](https://user-images.githubusercontent.com/18512224/39969749-fe4f92ee-56e0-11e8-8f14-03ac14d565a2.jpg)

I recognized, that sometimes, when i load my Ionic App, the css wasn't applied and it run back to your defined css styles. Why is this happening and can you help me to fix the default style with my style?

Thanks in regards.
Rebar
